# Generated by Django 2.0.10 on 2019-02-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='uplode_images',
            field=models.ImageField(blank=True, default='pic_folder/None/no-img.jpg', null=True, upload_to='pic_folder/'),
        ),
    ]
